<html>
<head>
<link rel=stylesheet" href="index.css">
</head>
<body><h1>Bem-vindo!</h1>
<p>Esse é o controlador do porteiro eletrônico. Use os botões abaixo para ir a ação que deseja. </p>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'senha', 'action' => 'cadastrar'), null, true) ?>" class="btn">Cadastrar</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'senha', 'action' => 'editar'), null, true) ?>" class="btn">Editar</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'senha', 'action' => 'remover'), null, true) ?>" class="btn">Remover</a>
</body>
</html>
