<html>
<head>
        <link rel=stylesheet" href="index.css">
        <script type="text/javascript" src="/snep/modules/porteiro/jquery/datatables.min.js"></script>
        <script type="text/javascript" src="/snep/modules/porteiro/jquery/jquery.dataTables.min.css"></script>
        <script type='text/javascript'>
                jQuery(document).ready(function(){
                        jQuery('#example').DataTable();
});
</script>
<meta charset="UTF-8"> 
</head>
<?php echo $this->text ?>
<?php echo $this->form ?>

<?
$bd = Zend_Registry::get('db');
$select = $bd->select()
                ->from('tb_porteiro');
$stmt = $bd->query($select);
$result = $stmt->fetchAll();
?>
<table id="example" class="display" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>Nome</th>
            <th>IP</th>
            <th>MAC</th>
            <th>Porta</th>
            <th>Transporte</th>
            <th>Rele1</th>
            <th>Rele2</th>
            <th>Cadastro</th>
            <th>Atualizado</th>
        </tr>
    </thead>
    <tbody>
        <?
                foreach ($result as $row)
                {
                ?>
                        <tr>
                                <td><?=$row['nome']?></td>
                                <td><?=$row['ip']?></td>
                                <td><?=$row['mac']?></td>
                                <td><?=$row['porta']?></td>
                                <td><?=$row['transporte']?></td>
                                <td><?=$row['rele1']?></td>
                                <td><?=$row['rele2']?></td>
                                <td><?=$row['cadastro']?></td>
                                <td><?=$row['atualizado']?></td>
                        </tr>
                <? } ?>
    </tbody>
</table>

</body>
</html>

