<html>
<head>
        <link rel=stylesheet" href="index.css">
        <script type="text/javascript" src="/snep/modules/porteiro/jquery/datatables.min.js"></script>
        <script type="text/javascript" src="/snep/modules/porteiro/jquery/jquery.dataTables.min.css"></script>
        <script type='text/javascript'>
                jQuery(document).ready(function(){
                        jQuery('#example').DataTable();

	</script>
	<meta charset="UTF-8">
<style>
.dataTables_length, .dataTables_filter,td, tr, th{ 
        text-align: center;
}
.dataTables_paginate, .dataTables_info{
        text-align: center;
        align: center;
}

#divform{
	
	left:50%;
	align:center;
}

</style>
 
</head>
<?php echo $this->text ?>
<div id="divform">
<?php echo $this->form ?>
</div>
<?
$result = Gerenciador_Manager::getTabela('tb_grupos');
?>
<table id="example" class="display" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>Grupo</th>
            <th>Cadastro</th>
            <th>Atualizado</th>
        </tr>
    </thead>
    <tbody>
        <?
                foreach ($result as $row)
                {
                ?>
                        <tr>
                                <td><a id="<?=$row['grupo']?>" class="red" href="/snep/index.php/porteiro/gerenciador/permissoes?grupo=<?=$row['grupo']?>">&nbsp &nbsp &nbsp <?=$row['grupo']?></a></td>
                                <td><?=$row['cadastro']?></td>
                                <td><?=$row['atualizado']?></td>
                        </tr>
                <? } ?>
    </tbody>
</table>

</body>
</html>

