<html>
<head>
        <link rel=stylesheet" href="index.css">
        <script type="text/javascript" src="/snep/modules/porteiro/jquery/datatables.min.js"></script>
        <script type="text/javascript" src="/snep/modules/porteiro/jquery/jquery.dataTables.min.css"></script>
        <script type='text/javascript'>
                jQuery(document).ready(function(){
                        jQuery('#example').DataTable();

			jQuery('.red').click(function(){
				var id = $(this).attr('id');
				
				//falta transformar isso para uma string e enviar//
				//$.post($this->_redirect('/porteiro/gerenciador/permissoes/grupo/'.id)
			});
		});
	</script>
<meta charset="UTF-8"> 
</head>
<?php echo $this->text ?>
<?php echo $this->form ?>

<?
$bd = Zend_Registry::get('db');
$select = $bd->select()
                ->from('tb_grupos');
$stmt = $bd->query($select);
$result = $stmt->fetchAll();
?>
<table id="example" class="display" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>Grupo</th>
            <th>Cadastro</th>
            <th>Atualizado</th>
        </tr>
    </thead>
    <tbody>
        <?
                foreach ($result as $row)
                {
                ?>
                        <tr>
                                <td><a id="<?=$row['grupo']?>" class="red" href="<?php //echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'permissoes'), null, true) ?>">&nbsp &nbsp &nbsp <?=$row['grupo']?></a></td>
                                <td><?=$row['cadastro']?></td>
                                <td><?=$row['atualizado']?></td>
                        </tr>
                <? } ?>
    </tbody>
</table>

</body>
</html>

