<html>
<head>
<link rel=stylesheet" href="index.css">
<style>
p, h1, div{
        text-align:center;
        align:center;
}
</style>

</head>
<body><h1>Erro! Um campo foi preenchido errado!</h1>
<div>
<a class="btn btn-outline btn-add" href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'cadastrarporteiro'), null, true) ?>">Retornar</a>
</div>



</body>
</html>

