<html>
<head>
        <link rel=stylesheet" href="index.css">
        <script type="text/javascript" src="/snep/modules/porteiro/jquery/datatables.min.js"></script>
        <script type="text/javascript" src="/snep/modules/porteiro/jquery/jquery.dataTables.min.css"></script>
        <script type='text/javascript'>
                jQuery(document).ready(function(){
                        jQuery('#example').DataTable();
});
</script>
</head>
<body><h1>Gerenciador de porteiro eletrônico.</h1>
<p>Esse é o gerenciador do porteiro eletrônico. Use os botões abaixo para ir a ação que deseja. </p>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'cadastrarporteiro'), null, true) ?>" class="btn">Cadastrar Porteiro</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'removerporteiro'), null, true) ?>" class="btn">Remover Porteiro</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'editarporteiro'), null, true) ?>" class="btn">Editar Porteiro</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'cadastrargrupo'), null, true) ?>" class="btn">Cadastrar Grupo</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'removergrupo'), null, true) ?>" class="btn">Remover Grupo</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'permissoes'), null, true) ?>" class="btn">Permissoes</a>


<h1>&nbsp</h1>

<?
$bd = Zend_Registry::get('db');
$select = $bd->select()
                ->from('senha');
$stmt = $bd->query($select);
$result = $stmt->fetchAll();
?>
<table id="example" class="display" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>Usuário</th>
            <th>Grupo</th>
            <th>Cadastro</th>
            <th>Atualizado</th>
        </tr>
    </thead>
    <tbody>
        <?
                foreach ($result as $row)
                {
                ?>
                        <tr>
                                <td><?=$row['usuario']?></td>
                                <td><?=$row['grupo']?></td>
                                <td><?=$row['cadastro']?></td>
                                <td><?=$row['atualizado']?></td>
                        </tr>
                <? } ?>
    </tbody>
</table>

</body>
</html>
