<html>
<head>
</head>
<body><h1>Gerenciador de porteiro eletrônico.</h1>
<p>Esse é o gerenciador do porteiro eletrônico. Use os botões abaixo para ir a ação que deseja. </p>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'cadastrarporteiro'), null, true) ?>" class="btn">Cadastrar Porteiro</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'removerporteiro'), null, true) ?>" class="btn">Remover Porteiro</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'editarporteiro'), null, true) ?>" class="btn">Editar Porteiro</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'cadastrargrupo'), null, true) ?>" class="btn">Cadastrar Grupo</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'removergrupo'), null, true) ?>" class="btn">Remover Grupo</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'permissoes'), null, true) ?>" class="btn">Permissoes</a>


<h1>&nbsp</h1>
</body>
</html>
