<html>
<head>
</head>
<body><h1 align="center">Gerenciador de porteiro eletrônico.</h1>
<p align="center">Esse é o gerenciador do porteiro eletrônico. Use os botões abaixo para ir a ação que deseja. </p>
<div align="center">
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'cadastrarporteiro'), null, true) ?>" class="btn btn-outline btn-add">Cadastrar Porteiro</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'removerporteiro'), null, true) ?>" class="btn btn-outline btn-add">Remover Porteiro</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'editarporteiro'), null, true) ?>" class="btn btn-outline btn-add">Editar Porteiro</a> 
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'cadastrargrupo'), null, true) ?>" class="btn btn-outline btn-add">Cadastrar Grupo</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'gerenciador', 'action' => 'removergrupo'), null, true) ?>" class="btn btn-outline btn-add">Remover Grupo</a>
</div>


<h1>&nbsp</h1>
</body>
</html>
