<head>
<meta charset="UTF-8">
</head>
<body> 
<h1>Permissões</h1>
<?php
	$bd = Zend_Registry::get('db');
	$select = $bd->select()
	                ->from('tb_porteiro');
	$stmt = $bd->query($select);
	$result = $stmt->fetchAll();

?>
<form action="permissoes" method="post" enctype="application/x-www-form-urlencoded">
        <input type="hidden" name="grupo" value="<?echo $this->status?>">	
        <?  $num=1;
                foreach ($result as $row)
                {   
                ?> 
			<input type="checkbox" name="mac<?=$num?>" value="<?=$row['mac']?>"><?=$row['mac']?><br>
		<? $num = $num +1;} ?>
	<input type="submit" value="Enviar">
</form>
</body>
