<head>
<meta charset="UTF-8">
<link rel=stylesheet" href="index.css"> 
<script type="text/javascript" src="/snep/modules/porteiro/jquery/datatables.min.js"></script>
<script type="text/javascript" src="/snep/modules/porteiro/jquery/jquery.dataTables.min.css"></script>
<script type='text/javascript'>
        jQuery(document).ready(function(){
                jQuery('#example').DataTable();
});
</script>
<style>
.dataTables_length, .dataTables_filter,td, tr, th{ 
        text-align: center;
}
.dataTables_paginate, .dataTables_info{
        text-align: center;
        align: center;
}
</style>
</head> 
<?php echo $this->text ?>
<?php echo $this->form ?>
<p><p>

<?
$result = Gerenciador_Manager::getTabela('contador_senha');
?>
<table id="example" class="display" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>Data</th>
            <th>Porteiro</th>
            <th>Ramal</th>
            <th>Usuário</th>
            <th>Resultado</th>
        </tr>
    </thead>
    <tbody>
        <?
                foreach ($result as $row)
                {
                        $porteiro = Gerenciador_Manager::porteiroGetByID($row['id']);
			$usuario = Gerenciador_Manager::userGetById($row['id_senha']);
                ?>
                        <tr>
                                <td><?=$row['data']?></td>
                                <td><?=$porteiro['mac']?></td>
                                <td><?=$row['ramal']?></td>
                                <td><?=$usuario['usuario']?></td>
                                <td><?=$row['resultado']?></td>
                        </tr>
                <? } ?>
    </tbody>
</table>


