<html>
<head>

	<link rel=stylesheet" href="index.css">
	<script type="text/javascript" src="/snep/modules/porteiro/jquery/datatables.min.js"></script>
	<script type="text/javascript" src="/snep/modules/porteiro/jquery/jquery.dataTables.min.css"></script>
	<script type='text/javascript'>
		jQuery(document).ready(function(){
   			jQuery('#example').DataTable();
});
</script>
<style>
.dataTables_length, .dataTables_filter,td, tr, th{ 
        text-align: center;
}
.dataTables_paginate, .dataTables_info, #example_wrapper{
        text-align: center;
        align: center;
}
</style>


</head>
<body><h1 align="center">Controlador via RFID.</h1>
<p align="center">Esse é o controlador do porteiro eletrônico. Use os botões abaixo para ir a ação que deseja. </p>


<div align="center">
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'rfid', 'action' => 'cadastrarrfid'), null, true) ?>" class="btn btn-outline btn-add">Cadastrar</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'rfid', 'action' => 'editarrfid'), null, true) ?>" class="btn btn-outline btn-add">Editar</a>
<a href="<?php echo $this->url(array('module' => 'porteiro', 'controller' => 'rfid', 'action' => 'removerrfid'), null, true) ?>" class="btn btn-outline btn-add">Remover</a>
<h1>&nbsp</h1>
</div>
<?
$result = Rfid_Database::getTabela('rfid');
?>
<table id="example" class="display" width="100%" cellspacing="0">
    <thead>
	<tr>

            <th>RFID</th>
            <th>Grupo</th>
            <th>Cadastro</th>
	    <th>Atualizado</th>
        </tr>
    </thead>
    <tbody>
	<?
		foreach ($result as $row)
		{
		?>
        		<tr>
            			<td><?=$row['rfid']?></td>
            			<td><?=$row['grupo']?></td>
            			<td><?=$row['cadastro']?></td>
				<td><?=$row['atualizado']?></td>
        		</tr>
		<? } ?>
    </tbody>
</table>

</body>
</html>
