<head>
<meta charset="UTF-8">
<script type="text/javascript" src="/snep/modules/porteiro/jquery/datatables.min.js"></script>
<script type="text/javascript" src="/snep/modules/porteiro/jquery/jquery.dataTables.min.css"></script>
<script type='text/javascript'>
                jQuery(document).ready(function(){
                        jQuery('#example').DataTable();
});

</script>
<style>
.dataTables_length, .dataTables_filter,td, tr, th{ 
        text-align: center;
}
.dataTables_paginate, .dataTables_info{
        text-align: center;
        align: center;
}
</style>


</head> 
<?php echo $this->text ?>
<?php echo $this->form ?>

<?
$result = Rfid_Database::getTabela('rfid');
?>
<table id="example" class="display" width="100%" cellspacing="0">
    <thead>
        <tr>

            <th>RFID</th>
            <th>Grupo</th>
            <th>Cadastro</th>
            <th>Atualizado</th>
        </tr>
    </thead>
    <tbody>
        <?  
                foreach ($result as $row)
                {   
                ?>  
                        <tr>
                                <td><?=$row['rfid']?></td>
                                <td><?=$row['grupo']?></td>
                                <td><?=$row['cadastro']?></td>
                                <td><?=$row['atualizado']?></td>
                        </tr>
                <? } ?>
    </tbody>
</table>


